services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5435:5435"
    restart: always
    networks:
      - rates_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    networks:
      - rates_network
  
  ingest:
    build:
      context: ingest
      dockerfile: ./Dockerfile
    environment:
      - INSTANCE_HOST=${INSTANCE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - TABLE_NAME=${TABLE_NAME}
    depends_on:
      - db
      - pgadmin
    networks:
      - rates_network

  pnl_calc:
    build:
      context: ./pnl
      dockerfile: ./Dockerfile
    environment:
      - INSTANCE_HOST=${INSTANCE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
      - X_API_KEY=${X_API_KEY}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - TABLE_NAME=${TABLE_NAME}
    depends_on:
      ingest:
        condition: service_completed_successfully

    networks:
      - rates_network
  
networks:
  rates_network:
    name: rates_default_network